# -*- coding: utf-8 -*-
"""IoT Sensor Data Monitoring .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ez1SowRl_RrGqrFEUeV2j6sWM2GfSNcs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest

np.random.seed(42)

time = np.arange(1, 101)

# Normal temperature readings
temp = np.random.normal(35, 2, 100)

# Normal vibration readings
vibration = np.random.normal(10, 1, 100)

# Add anomalies
temp[20] = 55
temp[60] = 60

vibration[30] = 25
vibration[80] = 28

data = pd.DataFrame({
    "Time": time,
    "Temperature": temp,
    "Vibration": vibration
})

print(data.head())

plt.figure(figsize=(10,5))

plt.plot(data["Time"], data["Temperature"], label="Temperature")
plt.plot(data["Time"], data["Vibration"], label="Vibration")

plt.title("IoT Sensor Monitoring Dashboard")
plt.xlabel("Time")
plt.ylabel("Sensor Values")
plt.legend()
plt.grid(True)

plt.show()

model = IsolationForest(contamination=0.05, random_state=42)

data["Anomaly"] = model.fit_predict(data[["Temperature", "Vibration"]])

anomalies = data[data["Anomaly"] == -1]
print(anomalies)

plt.figure(figsize=(10,5))

plt.plot(data["Time"], data["Temperature"], label="Temperature")
plt.scatter(anomalies["Time"], anomalies["Temperature"], color='red', label="Anomaly")

plt.title("Temperature Anomaly Detection")
plt.xlabel("Time")
plt.ylabel("Temperature")
plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(10,5))

plt.plot(data["Time"], data["Vibration"], label="Vibration")
plt.scatter(anomalies["Time"], anomalies["Vibration"], color='red', label="Anomaly")

plt.title("Vibration Anomaly Detection")
plt.xlabel("Time")
plt.ylabel("Vibration")
plt.legend()
plt.grid(True)

plt.show()

for i in anomalies.index:
    print(f"⚠ ALERT: Anomaly detected at Time {data['Time'][i]}")